In [2]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])

idx = np.array([True, False ,True, False, True,
                False,True,False,True,False])
a[idx]


array([0, 2, 4, 6, 8])

불리안 배열
> 불리안 배열의 인덱싱 방식은 인덱스 배열의 원소가 True와 False만으로 구성되며
인덱스 배열의 크기가 원래 ndarry 객체의 크기와 같아야 한다


In [4]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[:, [True, False, True, False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [12]:
x = np.array([1,2,3,4,5,6,7,8,9,10,
              11,12,13,14,15,16,17,18,19,20])

In [19]:
a = x % 3 == 0

b = x % 4 == 1

c = x[(x % 3 ==0)&(x % 4 == 1)]

In [20]:
print(x[p])

[ 3  6  9 12 15 18]


In [21]:
print(x[b]), print(x[c])

[ 1  5  9 13 17]
[10]


(None, None)