# [Numpy](https://numpy.org/devdocs/user/index.html)

>Numpy는 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 C언어 로 구성된 파이썬의 라이브러리이다. 데이터 구조 외에도 고성능의 수치 계산을 위해 사용한다.

>Numercial Python의 줄임말이며, 벡터 및 행렬 연산에 있어서 매우 편리하다.

>배열을 생성하고 기술 통계를 낼 수 있으며, 난수를 발생하고 그 결과를 분석하는데 유용하다

>모든 배열의 값이 기본적으로 같은 타입이여야 한다 


###numpy.ndarray(3차원, n차원 배열 객체)
>python 과의 차이로는 ndarray는 하나의 데이터 타입만 넣을 수 있다.
c언어의 행렬(모든 원소가 자료형)처럼 연속적인 메모리 배치를 가진다 제약이 있지만 내부 원소에 대한 접근과 반복문 실행이 빠르다 
- {np.ndarray}.shape: 
{}의 형태를 tuple로 반환
- {np.ndarray}.ndim: 
{}의 차원을 int로 반환
-{np.ndarray}.sizq: 
{}데이터의 수를 int로 반환
-{np.ndarray}.tolist: 
{}의 데이터들을 list로 반환
-list({{np.ndarray}.nbytes}): 
({})의 데이터 list 화
-{np.ndarray}.dtype:
{}의 데이터 타입을 반환


### 스칼라, 벡터, 행렬

- 스칼라(scarlar)란
  - 간단하게 하나의 값



-벡터(vector):
  - 1차원 데이터
  - 스칼라가 연속적으로 모여 있는것들

-행렬(matrix):
  - 2차원 데이터
  - 행과 열을 벡터로 해석 가능

#배열생성

In [1]:
import numpy as np 

In [2]:
scalar = 1
scalar

1

In [12]:
list = [1,4,5,6]

vector = np.array(list)
vector

array([1, 4, 5, 6])

In [13]:
vector.shape

(4,)

In [18]:
vector.dtype 
### 비트 타입은 자동적으로 지정 but 데이터 용량에 유리 따라서 비트를 할당해주는것이 작업에 유리 

dtype('int64')

In [19]:
lst = [
    [1,2,3],
    [4,5,6]
]                   #array로 리스트를 만드는 것은 파이썬으로 생성했지만 np가 이해할 수 있는 파일이다. 
arr = np.array(lst) #대괄호 두개의 의미는 2차원 array를 의미한다. 
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
lst

[[1, 2, 3], [4, 5, 6]]

In [28]:
arr.size #데이터의 수량을 의미

6

In [30]:
arr.ndim #ndim = array dimensin(배열의 차원)
          #3차원의 경우 fram, vector, scarlar으로 볼 수 있다. 

2

In [31]:
arr.shape #배열 차원의 튜플
          #몇 행 몇 열인지 반환

(2, 3)

In [34]:
arr[0,0] #2차원 배열의 접근방법
        #만약 3차원이라면 (frame, vector, scarlar)으로 접근하면 된다.

1

In [36]:
arr1= np.arange(10) # 0에서 부터 1씩 증가하는 1차원 배열
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [44]:
rg = np.random.default_rng(1) #ra

In [46]:
np.floor(10* rg.random((2,2)))

array([[5., 9.],
       [1., 9.]])

In [47]:
np.zeros((5,3)) #영행렬 0으로 가득찬 행렬 np.zeros(shape, dtype, order)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((2,3)) #유닛행렬 1로 가득 np.ones(shape, dtype, order)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.full((2,3), 5) #모든 원소가 5인 2x3 행렬

array([[5, 5, 5],
       [5, 5, 5]])

In [50]:
np.eye(2) # 단위행렬

array([[1., 0.],
       [0., 1.]])

In [52]:
np.eye(3,3) # np.eye(n,m,k) n=row m=행렬 k=시작행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#배열 결합

In [55]:
arr1 = np.array([[1,1],
                 [2,2]])
arr2 = np.array([[3,3],
                 [4,4]])

In [57]:
np.vstack((arr1,arr2)) # 수직으로 stack 해줘 

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
np.hstack((arr1,arr2)) # v와 반대로

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

#배열의 차원 변환

In [60]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
arr.base

In [62]:
arr.shape

(20,)

#차원 추가

In [63]:
arr[:,np.newaxis].shape #newaxis: np행렬의 차원을 확장하는 함수

# -> : 특정 차원의 배열을 전체 선택하기 위해 쓰는 연산자

(20, 1)

In [70]:
np.expand_dims(arr, axis=1).shape

(20, 1)

In [71]:
np.expand_dims(arr, axis=0).shape

(1, 20)

In [73]:
arr.resize((5,4)) # 5x4 행렬
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [75]:
arr.ravel() #다차원 배열을 1차원 배열로 만들어 준다

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
arr.T #returns the array, transposed, 개념만 이해

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [77]:
arr.reshape(4,5) #데이터의 변경 없이 shape 만 바꿔준다. 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [80]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#데이터 타입

In [82]:
arr.dtype #arr 데이터 확인

dtype('int64')

#슬라이싱, 인덱싱
-파이썬에서의 개념과 똑같다

#배열 조건 연산

In [84]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr # 모양은 (3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
arr[arr<5] #이와 같인 조건으로도 생성이 가능하다

array([1, 2, 3, 4])

In [86]:
arr[arr%2 ==0]

array([ 2,  4,  6,  8, 10, 12])

In [87]:
cond = (arr > 2) & (arr < 11) #and의 의미
arr[cond]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
cond = (arr > 2) & (arr < 11) #or의 의미
arr[cond]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
np.any(arr>5) # 조건 중에서 참이 하나라도 있다면 True

True

In [91]:
np.all(arr <5) #조건이 모두 참이라면 True

False

In [92]:
np.where(arr>5,1,0) #where(조건, 참인경우, 거짓경우)

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

In [93]:
np.clip(arr, 5, 8) # np.clip(array, min, max) min보다 작으면 min으로 max보다 크면 max로

array([[5, 5, 5, 5],
       [5, 6, 7, 8],
       [8, 8, 8, 8]])

In [95]:
#np.inf: 무한
#np.nan: 결측치 Not a number의 약어로 표현 불가능한 수치형 결과를 말한다 

In [96]:
arr = np.array([np.inf, np.nan, 3,4,5, np.nan,6,7])
arr

array([inf, nan,  3.,  4.,  5., nan,  6.,  7.])

In [99]:
is_inf = np.isinf(arr) # isinf 이게 무한인가 아닌가를 묻는 함수
np.any(is_inf), np.all(is_inf)

(True, False)

In [101]:
is_nan = np.isnan(arr) # isnan 이하 동문
np.any(is_nan), np.all(is_nan)

(True, False)

In [102]:
np.isfinite(arr) #셀수 있는 수 찾기

array([False, False,  True,  True,  True, False,  True,  True])

In [103]:
arr[np.isfinite(arr) == False] = 0 #셀수 없는 숫자의 경우 0으로 바꿔줘라 
arr  #무한 & nan값을 0으로 변경

array([0., 0., 3., 4., 5., 0., 6., 7.])

In [104]:
is_inf = np.isinf(arr)
np.any(is_nan), np.all(is_nan)

(True, False)

#마스킹


#numpy.ma 모듈
- 불안전 혹은 유효하지 않은 데이터로 오염될 경우를 배제하기 위해 쓰는 함수 

In [106]:
list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr = np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
mask = [True,False,True]
arr[...,mask]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [113]:
mask = arr>5 #조건을 사용하여 
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [114]:
arr[mask] #위의 함수식이 적용된 결과 

array([6, 7, 8, 9])

#Broadcasting
-

-특정 제약사항을 조건으로 shape이 다른 두 array가 호환되는 shape을 가지도록 작은 쪽에서 큰 쪽으로 boradcast 하는 것을 의미한다.


In [116]:
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([2.0, 2.0, 2.0])
arr1 * arr2
#arr1 *2 와 결과 값이 같다

array([2., 4., 6.])

In [117]:
arr1 = np.array([
          [ 0.0,  0.0,  0.0],
          [10.0, 10.0, 10.0],
          [20.0, 20.0, 20.0],
          [30.0, 30.0, 30.0]
        ])
arr2 = np.array([1.0,2.0,3.0])
arr1 + arr2

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])